module full_adder(
    input wire a,      // Input a
    input wire b,      // Input b
    input wire c,      // Input carry-in
    output wire sum,   // Output sum
    output wire carry   // Output carry-out
);

    // Calculate sum and carry
    assign sum = (a ^ b) ^ c;  // Sum is the XOR of a, b, and c
    assign carry = (a & b) | (c & (a ^ b));  // Carry is generated by AND and OR operations

endmodule